#ifndef ANTS_CONSTANTS_H
#define ANTS_CONSTANTS_H

#define LIFETIME_QUEEN 10*365*24
#define LIFETIME_OTHER 365*24
#define LIFETIME_SLAVER 10*24

#define ADULT_WORKER 15 * 24
#define ADULT_SCOUT 2 * 24

#define DISPLAY_CELL_X 40
#define DISPLAY_CELL_Y 40
#define DISPLAY_CELL_SIZE 16

#define GAME_WIDTH DISPLAY_CELL_X*DISPLAY_CELL_SIZE
#define GAME_HEIGHT DISPLAY_CELL_Y*DISPLAY_CELL_SIZE

#define WINDOW_WIDTH GAME_WIDTH
#define STATUS_BAR_HEIGHT 50
#define WINDOW_HEIGHT GAME_HEIGHT+STATUS_BAR_HEIGHT

#define SHIFT_SPEED 4

#define CELL_EMPTY 1
#define CELL_OBSTACLE 4
#define CELL_ANTHILL 14
#define CELL_FOOD 166

#define ANTHILL_ANTS_CAPACITY 100
#define OTHER_ANTS_CAPACITY 8

#define WORKER_PHEROMONE_MAX 500
#define WORKER_PHEROMONE_DROP_RATE 0.005

#endif